# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 111, 16))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 50, 198, 115))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelHarga = QtWidgets.QLabel(self.widget)
        self.labelHarga.setObjectName("labelHarga")
        self.gridLayout.addWidget(self.labelHarga, 0, 0, 1, 1)
        self.lineEditHarga = QtWidgets.QLineEdit(self.widget)
        self.lineEditHarga.setObjectName("lineEditHarga")
        self.gridLayout.addWidget(self.lineEditHarga, 0, 1, 1, 1)
        self.labelPajak = QtWidgets.QLabel(self.widget)
        self.labelPajak.setObjectName("labelPajak")
        self.gridLayout.addWidget(self.labelPajak, 1, 0, 1, 1)
        self.comboBoxPajak = QtWidgets.QComboBox(self.widget)
        self.comboBoxPajak.setObjectName("comboBoxPajak")
        self.comboBoxPajak.addItem("")
        self.comboBoxPajak.addItem("")
        self.comboBoxPajak.addItem("")
        self.gridLayout.addWidget(self.comboBoxPajak, 1, 1, 1, 1)
        self.pushButtonHitung = QtWidgets.QPushButton(self.widget)
        self.pushButtonHitung.setObjectName("pushButtonHitung")
        self.gridLayout.addWidget(self.pushButtonHitung, 2, 1, 1, 1)
        self.labelTotal = QtWidgets.QLabel(self.widget)
        self.labelTotal.setObjectName("labelTotal")
        self.gridLayout.addWidget(self.labelTotal, 3, 0, 1, 2)
        self.labelHasil = QtWidgets.QLabel(self.widget)
        self.labelHasil.setText("")
        self.labelHasil.setObjectName("labelHasil")
        self.gridLayout.addWidget(self.labelHasil, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hitung Pajak"))
        self.label.setText(_translate("MainWindow", "Hitung Pajak :"))
        self.labelHarga.setText(_translate("MainWindow", "Harga (Rp):"))
        self.labelPajak.setText(_translate("MainWindow", "Pajak (%):"))
        self.comboBoxPajak.setItemText(0, _translate("MainWindow", "5%"))
        self.comboBoxPajak.setItemText(1, _translate("MainWindow", "10%"))
        self.comboBoxPajak.setItemText(2, _translate("MainWindow", "15%"))
        self.pushButtonHitung.setText(_translate("MainWindow", "Hitung Pajak"))
        self.labelTotal.setText(_translate("MainWindow", "Total Harga dengan Pajak:"))
